// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class AdminConfiguration_GetCompanyByUrlReturnModel
    {
        public System.Int64 CompanyID { get; set; }
        public System.String CompanyName { get; set; }
        public System.String CompanyUrl { get; set; }
        public System.Int32? CompanyStatus { get; set; }
        public System.String PrivateConnectionString { get; set; }
    }

}
// </auto-generated>
