// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_ZooStudentDocuments
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Citizen_TblZooStudentDocumentConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Citizen_TblZooStudentDocument>
    {
        public Citizen_TblZooStudentDocumentConfiguration()
            : this("Citizen")
        {
        }

        public Citizen_TblZooStudentDocumentConfiguration(string schema)
        {
            ToTable("tbl_ZooStudentDocuments", schema);
            HasKey(x => x.ZooStudentId);

            Property(x => x.ZooStudentId).HasColumnName(@"ZooStudentId").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ZooBookingId).HasColumnName(@"ZooBookingId").HasColumnType("bigint").IsRequired();
            Property(x => x.IdDocument).HasColumnName(@"IDDocument").HasColumnType("nvarchar").IsRequired().HasMaxLength(500);
        }
    }

}
// </auto-generated>
