// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // The table 'TBL_ZOOTICKETRDLC' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // TBL_ZOOTICKETRDLC
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Citizen_TblZooticketrdlc
    {
        public string PlaceName { get; set; } // PlaceName (length: 150)
        public string RequestId { get; set; } // RequestId (length: 150)
        public string ZooBookingId { get; set; } // ZooBookingId (length: 150)
        public string DateOfVisit { get; set; } // DateOfVisit (length: 150)
        public string VisitTime { get; set; } // VisitTime (length: 150)
        public string InstitutionalNameofHead { get; set; } // Institutional_NameofHead (length: 150)
        public string InstitutionalHeadIdNumber { get; set; } // Institutional_HeadIdNumber (length: 150)
        public string InstitutionalHeadIdType { get; set; } // Institutional_HeadIdType (length: 150)
        public string HeadeText { get; set; } // HeadeText
        public string FooterText { get; set; } // FooterText
        public string TypeOfMember { get; set; } // TypeOfMember (length: 150)
        public int? NoOfMember { get; set; } // NoOfMember
        public int? FeePerMember { get; set; } // FeePerMember
        public int? TotalMemberFees { get; set; } // TotalMemberFees
    }

}
// </auto-generated>
