// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_TicketBookingMembers
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Citizen_TblTicketBookingMember
    {
        public long MemberId { get; set; } // MemberID (Primary key)
        public long TicketId { get; set; } // TicketID
        public string Name { get; set; } // Name (length: 100)
        public string Gender { get; set; } // Gender (length: 50)
        public string IdType { get; set; } // IDType (length: 50)
        public string IdNo { get; set; } // IDNo (length: 50)
        public string Nationality { get; set; } // Nationality (length: 50)
        public string MemberType { get; set; } // MemberType (length: 50)
        public string MemberIdProof { get; set; } // MemberIDProof
        public decimal? FeePerMember { get; set; } // FeePerMember
        public int? NoOfCamera { get; set; } // NoOfCamera
        public int? Isactive { get; set; } // Isactive
        public System.DateTime? EnteredOn { get; set; } // EnteredOn
        public long? EnteredBy { get; set; } // EnteredBy
        public System.DateTime? UpdatedOn { get; set; } // UpdatedOn
        public long? UpdatedBy { get; set; } // UpdatedBy
        public int? BoardingZoneId { get; set; } // BoardingZoneID
        public bool? ZoneUpdateStatus { get; set; } // ZoneUpdateStatus
        public bool? BoardingIssueStatus { get; set; } // BoardingIssueStatus
        public string BoardingId { get; set; } // BoardingID (length: 50)
        public string GuidName { get; set; } // GuidName (length: 150)
        public string VehicleNumber { get; set; } // VehicleNumber (length: 150)
        public long? MappingGvid { get; set; } // MappingGVID
        public bool NotArrivedOnBoardingTimeStatus { get; set; } // NotArrivedOnBoardingTimeStatus

        // Reverse navigation

        /// <summary>
        /// Child Citizen_TblWildLifeSafariBookingDetails where [tbl_WildLifeSafariBookingDetails].[MemberID] point to this entity (0MemberIDPK)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Citizen_TblWildLifeSafariBookingDetail> Citizen_TblWildLifeSafariBookingDetails { get; set; } // tbl_WildLifeSafariBookingDetails.0MemberIDPK
        /// <summary>
        /// Child Citizen_TblWildLifeTicketBookingMemberDetails where [tbl_WildLifeTicketBookingMemberDetails].[MemberID] point to this entity (MemberIDPK)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Citizen_TblWildLifeTicketBookingMemberDetail> Citizen_TblWildLifeTicketBookingMemberDetails { get; set; } // tbl_WildLifeTicketBookingMemberDetails.MemberIDPK

        public Citizen_TblTicketBookingMember()
        {
            Isactive = 1;
            EnteredOn = System.DateTime.Now;
            BoardingZoneId = 1;
            ZoneUpdateStatus = false;
            BoardingIssueStatus = false;
            GuidName = "";
            VehicleNumber = "";
            MappingGvid = 0;
            NotArrivedOnBoardingTimeStatus = true;
            Citizen_TblWildLifeSafariBookingDetails = new System.Collections.Generic.List<Citizen_TblWildLifeSafariBookingDetail>();
            Citizen_TblWildLifeTicketBookingMemberDetails = new System.Collections.Generic.List<Citizen_TblWildLifeTicketBookingMemberDetail>();
        }
    }

}
// </auto-generated>
