// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // ZooSeatInventory_OLD
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Citizen_ZooSeatInventoryOldConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Citizen_ZooSeatInventoryOld>
    {
        public Citizen_ZooSeatInventoryOldConfiguration()
            : this("Citizen")
        {
        }

        public Citizen_ZooSeatInventoryOldConfiguration(string schema)
        {
            ToTable("ZooSeatInventory_OLD", schema);
            HasKey(x => x.ZooSeatInventoryId);

            Property(x => x.ZooSeatInventoryId).HasColumnName(@"ZooSeatInventoryId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.PlaceId).HasColumnName(@"PlaceId").HasColumnType("bigint").IsRequired();
            Property(x => x.OnlineZooSeats).HasColumnName(@"OnlineZooSeats").HasColumnType("int").IsRequired();
            Property(x => x.OffLineZooSeats).HasColumnName(@"OffLineZooSeats").HasColumnType("int").IsRequired();
            Property(x => x.IsActive).HasColumnName(@"isActive").HasColumnType("bit").IsRequired();
        }
    }

}
// </auto-generated>
