// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_WildLifeSafariBookingDetails
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Citizen_TblWildLifeSafariBookingDetail
    {
        public long Rowid { get; set; } // ROWID (Primary key)
        public long MemberId { get; set; } // MemberID
        public long FeesId { get; set; } // FeesID
        public int WildLifeHeadDetailId { get; set; } // WildLifeHeadDetailID
        public double Price { get; set; } // Price
        public short Counts { get; set; } // Counts
        public bool IsActive { get; set; } // isActive

        // Foreign keys

        /// <summary>
        /// Parent Citizen_TblTicketBookingMember pointed by [tbl_WildLifeSafariBookingDetails].([MemberId]) (0MemberIDPK)
        /// </summary>
        public virtual Citizen_TblTicketBookingMember Citizen_TblTicketBookingMember { get; set; } // 0MemberIDPK
        /// <summary>
        /// Parent Master_TblMstTicketingFee pointed by [tbl_WildLifeSafariBookingDetails].([FeesId]) (0FEESIDPK)
        /// </summary>
        public virtual Master_TblMstTicketingFee Master_TblMstTicketingFee { get; set; } // 0FEESIDPK
        /// <summary>
        /// Parent Master_TblMstWildLifeHeadDetail pointed by [tbl_WildLifeSafariBookingDetails].([WildLifeHeadDetailId]) (0WildLifeHeadDetailsFK)
        /// </summary>
        public virtual Master_TblMstWildLifeHeadDetail Master_TblMstWildLifeHeadDetail { get; set; } // 0WildLifeHeadDetailsFK

        public Citizen_TblWildLifeSafariBookingDetail()
        {
            FeesId = 0;
            WildLifeHeadDetailId = 0;
            Price = 0;
            Counts = 0;
            IsActive = true;
        }
    }

}
// </auto-generated>
