// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_ZooMemberDetails
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Citizen_TblZooMemberDetail
    {
        public long ZooMemberId { get; set; } // ZooMemberId (Primary key)
        public long? BookingId { get; set; } // BookingId
        public string TypeOfMember { get; set; } // TypeOfMember (length: 50)
        public int? NoOfMember { get; set; } // NoOfMember
        public int? FeePerMember { get; set; } // FeePerMember
        public int? NoOfVideoCamera { get; set; } // NoOfVideoCamera
        public int? FeePerVideoCamera { get; set; } // FeePerVideoCamera
        public decimal? TotalFees { get; set; } // TotalFees
        public int NoOfStillCamera { get; set; } // NoOfStillCamera
        public int FeePerStillCamera { get; set; } // FeePerStillCamera

        public Citizen_TblZooMemberDetail()
        {
            BookingId = 0;
            TypeOfMember = "0";
            NoOfMember = 0;
            FeePerMember = 0;
            NoOfVideoCamera = 0;
            FeePerVideoCamera = 0;
            TotalFees = 0m;
            NoOfStillCamera = 0;
            FeePerStillCamera = 0;
        }
    }

}
// </auto-generated>
