// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_ZooBookingHeadDetailsTEMP
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Citizen_TblZooBookingHeadDetailsTemp
    {
        public long Id { get; set; } // ID (Primary key)
        public string RequestId { get; set; } // RequestId (length: 100)
        public int HeadId { get; set; } // HeadId
        public string FeeChargedOn { get; set; } // FeeChargedOn (length: 50)
        public string ParentFeeChargeOn { get; set; } // ParentFeeChargeOn (length: 50)
        public System.DateTime InsertDate { get; set; } // InsertDate
        public decimal HeadAmount { get; set; } // HeadAmount
        public int Counts { get; set; } // Counts

        public Citizen_TblZooBookingHeadDetailsTemp()
        {
            HeadId = 0;
            InsertDate = System.DateTime.Now;
            HeadAmount = 0m;
            Counts = 0;
        }
    }

}
// </auto-generated>
