// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_ZooMemberDetails
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Citizen_TblZooMemberDetailConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Citizen_TblZooMemberDetail>
    {
        public Citizen_TblZooMemberDetailConfiguration()
            : this("Citizen")
        {
        }

        public Citizen_TblZooMemberDetailConfiguration(string schema)
        {
            ToTable("tbl_ZooMemberDetails", schema);
            HasKey(x => x.ZooMemberId);

            Property(x => x.ZooMemberId).HasColumnName(@"ZooMemberId").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.BookingId).HasColumnName(@"BookingId").HasColumnType("bigint").IsOptional();
            Property(x => x.TypeOfMember).HasColumnName(@"TypeOfMember").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.NoOfMember).HasColumnName(@"NoOfMember").HasColumnType("int").IsOptional();
            Property(x => x.FeePerMember).HasColumnName(@"FeePerMember").HasColumnType("int").IsOptional();
            Property(x => x.NoOfVideoCamera).HasColumnName(@"NoOfVideoCamera").HasColumnType("int").IsOptional();
            Property(x => x.FeePerVideoCamera).HasColumnName(@"FeePerVideoCamera").HasColumnType("int").IsOptional();
            Property(x => x.TotalFees).HasColumnName(@"TotalFees").HasColumnType("decimal").IsOptional().HasPrecision(16,2);
            Property(x => x.NoOfStillCamera).HasColumnName(@"NoOfStillCamera").HasColumnType("int").IsRequired();
            Property(x => x.FeePerStillCamera).HasColumnName(@"FeePerStillCamera").HasColumnType("int").IsRequired();
        }
    }

}
// </auto-generated>
