// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_TicketBooking_Inventory
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Citizen_TblTicketBookingInventoryConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Citizen_TblTicketBookingInventory>
    {
        public Citizen_TblTicketBookingInventoryConfiguration()
            : this("Citizen")
        {
        }

        public Citizen_TblTicketBookingInventoryConfiguration(string schema)
        {
            ToTable("tbl_TicketBooking_Inventory", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.SDate).HasColumnName(@"sDate").HasColumnType("datetime").IsOptional();
            Property(x => x.VehicalId).HasColumnName(@"VehicalID").HasColumnType("int").IsOptional();
            Property(x => x.ShiftTime).HasColumnName(@"ShiftTime").HasColumnType("int").IsOptional();
            Property(x => x.CitizenMaxSeat).HasColumnName(@"CitizenMaxSeat").HasColumnType("int").IsOptional();
            Property(x => x.CitizenBookedSeat).HasColumnName(@"CitizenBookedSeat").HasColumnType("int").IsOptional();
            Property(x => x.KioskMaxSeat).HasColumnName(@"KioskMaxSeat").HasColumnType("int").IsOptional();
            Property(x => x.KioskBookedSeat).HasColumnName(@"KioskBookedSeat").HasColumnType("int").IsOptional();
        }
    }

}
// </auto-generated>
