// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_WildLifeTicketBookingMemberDetails
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Citizen_TblWildLifeTicketBookingMemberDetailConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Citizen_TblWildLifeTicketBookingMemberDetail>
    {
        public Citizen_TblWildLifeTicketBookingMemberDetailConfiguration()
            : this("Citizen")
        {
        }

        public Citizen_TblWildLifeTicketBookingMemberDetailConfiguration(string schema)
        {
            ToTable("tbl_WildLifeTicketBookingMemberDetails", schema);
            HasKey(x => x.Rowid);

            Property(x => x.Rowid).HasColumnName(@"ROWID").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.MemberId).HasColumnName(@"MemberID").HasColumnType("bigint").IsRequired();
            Property(x => x.FeesId).HasColumnName(@"FeesID").HasColumnType("bigint").IsRequired();
            Property(x => x.WildLifeHeadDetailId).HasColumnName(@"WildLifeHeadDetailID").HasColumnType("int").IsRequired();
            Property(x => x.Price).HasColumnName(@"Price").HasColumnType("float").IsRequired();
            Property(x => x.Counts).HasColumnName(@"Counts").HasColumnType("smallint").IsRequired();
            Property(x => x.IsActive).HasColumnName(@"isActive").HasColumnType("bit").IsRequired();

            // Foreign keys
            HasRequired(a => a.Citizen_TblTicketBookingMember).WithMany(b => b.Citizen_TblWildLifeTicketBookingMemberDetails).HasForeignKey(c => c.MemberId).WillCascadeOnDelete(false); // MemberIDPK
            HasRequired(a => a.Master_TblMstTicketingFee).WithMany(b => b.Citizen_TblWildLifeTicketBookingMemberDetails).HasForeignKey(c => c.FeesId).WillCascadeOnDelete(false); // FEESIDPK
            HasRequired(a => a.Master_TblMstWildLifeHeadDetail).WithMany(b => b.Citizen_TblWildLifeTicketBookingMemberDetails).HasForeignKey(c => c.WildLifeHeadDetailId).WillCascadeOnDelete(false); // WildLifeHeadDetailsFK
        }
    }

}
// </auto-generated>
