// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // Tbl_Cancel_requestedID
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Citizen_TblCancelRequestedId
    {
        public long Id { get; set; } // ID (Primary key)
        public string RequestedId { get; set; } // RequestedID (length: 50)
        public string Remarks { get; set; } // Remarks (length: 500)
        public bool Status { get; set; } // Status (Primary key)

        public Citizen_TblCancelRequestedId()
        {
            Status = false;
        }
    }

}
// </auto-generated>
