// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_TicketBookingMembers
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Citizen_TblTicketBookingMemberConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Citizen_TblTicketBookingMember>
    {
        public Citizen_TblTicketBookingMemberConfiguration()
            : this("Citizen")
        {
        }

        public Citizen_TblTicketBookingMemberConfiguration(string schema)
        {
            ToTable("tbl_TicketBookingMembers", schema);
            HasKey(x => x.MemberId);

            Property(x => x.MemberId).HasColumnName(@"MemberID").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.TicketId).HasColumnName(@"TicketID").HasColumnType("bigint").IsRequired();
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.Gender).HasColumnName(@"Gender").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.IdType).HasColumnName(@"IDType").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.IdNo).HasColumnName(@"IDNo").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Nationality).HasColumnName(@"Nationality").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.MemberType).HasColumnName(@"MemberType").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.MemberIdProof).HasColumnName(@"MemberIDProof").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.FeePerMember).HasColumnName(@"FeePerMember").HasColumnType("decimal").IsOptional().HasPrecision(18,2);
            Property(x => x.NoOfCamera).HasColumnName(@"NoOfCamera").HasColumnType("int").IsOptional();
            Property(x => x.Isactive).HasColumnName(@"Isactive").HasColumnType("int").IsOptional();
            Property(x => x.EnteredOn).HasColumnName(@"EnteredOn").HasColumnType("datetime").IsOptional();
            Property(x => x.EnteredBy).HasColumnName(@"EnteredBy").HasColumnType("bigint").IsOptional();
            Property(x => x.UpdatedOn).HasColumnName(@"UpdatedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.UpdatedBy).HasColumnName(@"UpdatedBy").HasColumnType("bigint").IsOptional();
            Property(x => x.BoardingZoneId).HasColumnName(@"BoardingZoneID").HasColumnType("int").IsOptional();
            Property(x => x.ZoneUpdateStatus).HasColumnName(@"ZoneUpdateStatus").HasColumnType("bit").IsOptional();
            Property(x => x.BoardingIssueStatus).HasColumnName(@"BoardingIssueStatus").HasColumnType("bit").IsOptional();
            Property(x => x.BoardingId).HasColumnName(@"BoardingID").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.GuidName).HasColumnName(@"GuidName").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(150);
            Property(x => x.VehicleNumber).HasColumnName(@"VehicleNumber").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(150);
            Property(x => x.MappingGvid).HasColumnName(@"MappingGVID").HasColumnType("bigint").IsOptional();
            Property(x => x.NotArrivedOnBoardingTimeStatus).HasColumnName(@"NotArrivedOnBoardingTimeStatus").HasColumnType("bit").IsRequired();
        }
    }

}
// </auto-generated>
