// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_DownloadTickets
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Citizen_TblDownloadTicket
    {
        public long Id { get; set; } // ID (Primary key)
        public string RequestedId { get; set; } // RequestedID (Primary key) (length: 50)
        public string TableName { get; set; } // TableName (Primary key) (length: 200)
        public short? ModuleId { get; set; } // ModuleId
        public short? ServiceTypeId { get; set; } // ServiceTypeId
        public short? PermissionId { get; set; } // PermissionId
        public short? SubPermissionId { get; set; } // SubPermissionId
        public string Path { get; set; } // Path (length: 500)
        public string PathRepoDocId { get; set; } // Path_RepoDocID (length: 500)
        public string PathName { get; set; } // Path_Name (length: 500)
        public string PathDocStatus { get; set; } // Path_DocStatus (length: 500)
        public bool? IsPdfStatus { get; set; } // IsPDFStatus
        public bool? Status { get; set; } // Status

        public Citizen_TblDownloadTicket()
        {
            PathDocStatus = "0";
        }
    }

}
// </auto-generated>
