// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_ZooStudentDocuments
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Citizen_TblZooStudentDocument
    {
        public long ZooStudentId { get; set; } // ZooStudentId (Primary key)
        public long ZooBookingId { get; set; } // ZooBookingId
        public string IdDocument { get; set; } // IDDocument (length: 500)

        public Citizen_TblZooStudentDocument()
        {
            ZooBookingId = 0;
        }
    }

}
// </auto-generated>
