// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_ZooVehicleDetails
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Citizen_TblZooVehicleDetailConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Citizen_TblZooVehicleDetail>
    {
        public Citizen_TblZooVehicleDetailConfiguration()
            : this("Citizen")
        {
        }

        public Citizen_TblZooVehicleDetailConfiguration(string schema)
        {
            ToTable("tbl_ZooVehicleDetails", schema);
            HasKey(x => x.ZooVehicleId);

            Property(x => x.ZooVehicleId).HasColumnName(@"ZooVehicleId").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.BookingId).HasColumnName(@"BookingId").HasColumnType("bigint").IsRequired();
            Property(x => x.VehicleType).HasColumnName(@"VehicleType").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.FeePerVehicle).HasColumnName(@"FeePerVehicle").HasColumnType("int").IsOptional();
            Property(x => x.NoOfVehicle).HasColumnName(@"NoOfVehicle").HasColumnType("int").IsOptional();
            Property(x => x.TotalVehicleFee).HasColumnName(@"TotalVehicleFee").HasColumnType("decimal").IsOptional().HasPrecision(16,2);
        }
    }

}
// </auto-generated>
