// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_PaymentByDepartmentalKioskUser
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Citizen_TblPaymentByDepartmentalKioskUser
    {
        public int RowId { get; set; } // RowId (Primary key)
        public int? ModuleId { get; set; } // ModuleId
        public int? ServiceTypeId { get; set; } // ServiceTypeId
        public int? PermissionId { get; set; } // PermissionId
        public int? SubpermissionId { get; set; } // SubpermissionId
        public string RequestedId { get; set; } // RequestedId (length: 50)
        public long? PaidForCitizen { get; set; } // PaidForCitizen
        public long? PaidBy { get; set; } // PaidBy
        public System.DateTime? PaidOn { get; set; } // PaidOn
        public decimal? PaidAmount { get; set; } // PaidAmount
        public string PaymentMode { get; set; } // PaymentMode (Primary key) (length: 50)
        public string BankName { get; set; } // BankName (length: 100)
        public string IfscCode { get; set; } // IFSCCode (length: 20)
        public string ChequeNumber { get; set; } // ChequeNumber (length: 50)
        public System.DateTime? ChequeDate { get; set; } // ChequeDate
        public string ReceiptNumber { get; set; } // ReceiptNumber (length: 50)
        public System.DateTime? EnteredDate { get; set; } // EnteredDate

        public Citizen_TblPaymentByDepartmentalKioskUser()
        {
            PaymentMode = "0";
        }
    }

}
// </auto-generated>
