// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // CompanyRagistration
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class CompanyRagistrationConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<CompanyRagistration>
    {
        public CompanyRagistrationConfiguration()
            : this("dbo")
        {
        }

        public CompanyRagistrationConfiguration(string schema)
        {
            ToTable("CompanyRagistration", schema);
            HasKey(x => x.CompanyId);

            Property(x => x.CompanyId).HasColumnName(@"CompanyID").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.CompanyName).HasColumnName(@"CompanyName").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.CompanyUrl).HasColumnName(@"CompanyUrl").HasColumnType("nvarchar").IsOptional().HasMaxLength(2000);
            Property(x => x.CompanyStatus).HasColumnName(@"CompanyStatus").HasColumnType("int").IsOptional();
            Property(x => x.PrivateConnectionString).HasColumnName(@"PrivateConnectionString").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(500);
        }
    }

}
// </auto-generated>
