// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_Mst_FixedPermission_Plant
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class GIS_TblMstFixedPermissionPlantConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<GIS_TblMstFixedPermissionPlant>
    {
        public GIS_TblMstFixedPermissionPlantConfiguration()
            : this("GIS")
        {
        }

        public GIS_TblMstFixedPermissionPlantConfiguration(string schema)
        {
            ToTable("tbl_Mst_FixedPermission_Plant", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.PlantName).HasColumnName(@"Plant_Name").HasColumnType("nchar").IsOptional().IsFixedLength().HasMaxLength(10);
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsOptional();
        }
    }

}
// </auto-generated>
