// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_mst_FixedPermissionTypes
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class GIS_TblMstFixedPermissionType
    {
        public int PId { get; set; } // P_ID (Primary key)
        public string Name { get; set; } // Name (length: 100)
        public string Status { get; set; } // Status (length: 50)
        public decimal? Amount { get; set; } // Amount
        public string Description { get; set; } // Description (length: 50)
        public int? Discount { get; set; } // Discount
        public decimal? Tax { get; set; } // Tax
        public System.DateTime? EnteredOn { get; set; } // EnteredOn
        public long? EnteredBy { get; set; } // EnteredBy
        public int? EmitraServiceId { get; set; } // EmitraServiceId

        public GIS_TblMstFixedPermissionType()
        {
            EnteredOn = System.DateTime.Now;
        }
    }

}
// </auto-generated>
