// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_Mst_FixedPermission_PlantMapping
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class GIS_TblMstFixedPermissionPlantMapping
    {
        public long Id { get; set; } // ID (Primary key)
        public string RequestedId { get; set; } // RequestedID (length: 100)
        public int? PlantId { get; set; } // PlantID
        public int? NumberTrees { get; set; } // Number_Trees
        public System.DateTime? EnteredOn { get; set; } // EnteredOn

        // Foreign keys

        /// <summary>
        /// Parent GIS_TblMstFixedPermissionPlant pointed by [tbl_Mst_FixedPermission_PlantMapping].([PlantId]) (FK_tbl_Mst_FixedPermission_PlantMapping_tbl_Mst_FixedPermission_Plant)
        /// </summary>
        public virtual GIS_TblMstFixedPermissionPlant GIS_TblMstFixedPermissionPlant { get; set; } // FK_tbl_Mst_FixedPermission_PlantMapping_tbl_Mst_FixedPermission_Plant

        public GIS_TblMstFixedPermissionPlantMapping()
        {
            EnteredOn = System.DateTime.Now;
        }
    }

}
// </auto-generated>
