// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    public partial interface Idb_FMDSS : System.IDisposable
    {
        System.Data.Entity.DbSet<AspNetRole> AspNetRoles { get; set; } // AspNetRoles
        System.Data.Entity.DbSet<AspNetUser> AspNetUsers { get; set; } // AspNetUsers
        System.Data.Entity.DbSet<AspNetUserClaim> AspNetUserClaims { get; set; } // AspNetUserClaims
        System.Data.Entity.DbSet<AspNetUserLogin> AspNetUserLogins { get; set; } // AspNetUserLogins
        System.Data.Entity.DbSet<Citizen_TblAssignGuideAndVehicleForDateOfVisite> Citizen_TblAssignGuideAndVehicleForDateOfVisites { get; set; } // tbl_AssignGuideAndVehicleForDateOfVisite
        System.Data.Entity.DbSet<Citizen_TblCancelRequestedId> Citizen_TblCancelRequestedIds { get; set; } // Tbl_Cancel_requestedID
        System.Data.Entity.DbSet<Citizen_TblDownloadTicket> Citizen_TblDownloadTickets { get; set; } // tbl_DownloadTickets
        System.Data.Entity.DbSet<Citizen_TblPaymentByDepartmentalKioskUser> Citizen_TblPaymentByDepartmentalKioskUsers { get; set; } // tbl_PaymentByDepartmentalKioskUser
        System.Data.Entity.DbSet<Citizen_TblPaymentByEmitraKioskUser> Citizen_TblPaymentByEmitraKioskUsers { get; set; } // tbl_PaymentByEmitraKioskUser
        System.Data.Entity.DbSet<Citizen_TblSafariBooking> Citizen_TblSafariBookings { get; set; } // tbl_SafariBooking
        System.Data.Entity.DbSet<Citizen_TblTicketBooking> Citizen_TblTicketBookings { get; set; } // tbl_TicketBooking
        System.Data.Entity.DbSet<Citizen_TblTicketBookingInventory> Citizen_TblTicketBookingInventories { get; set; } // tbl_TicketBooking_Inventory
        System.Data.Entity.DbSet<Citizen_TblTicketBookingMember> Citizen_TblTicketBookingMembers { get; set; } // tbl_TicketBookingMembers
        System.Data.Entity.DbSet<Citizen_TblWildLifeSafariBookingDetail> Citizen_TblWildLifeSafariBookingDetails { get; set; } // tbl_WildLifeSafariBookingDetails
        System.Data.Entity.DbSet<Citizen_TblWildLifeTicketBookingMemberDetail> Citizen_TblWildLifeTicketBookingMemberDetails { get; set; } // tbl_WildLifeTicketBookingMemberDetails
        System.Data.Entity.DbSet<Citizen_TblZooBooking> Citizen_TblZooBookings { get; set; } // tbl_ZooBooking
        System.Data.Entity.DbSet<Citizen_TblZooBookingHeadDetail> Citizen_TblZooBookingHeadDetails { get; set; } // tbl_ZooBookingHeadDetails
        System.Data.Entity.DbSet<Citizen_TblZooBookingHeadDetailsTemp> Citizen_TblZooBookingHeadDetailsTemps { get; set; } // tbl_ZooBookingHeadDetailsTEMP
        System.Data.Entity.DbSet<Citizen_TblZooMemberDetail> Citizen_TblZooMemberDetails { get; set; } // tbl_ZooMemberDetails
        System.Data.Entity.DbSet<Citizen_TblZooStudentDocument> Citizen_TblZooStudentDocuments { get; set; } // tbl_ZooStudentDocuments
        System.Data.Entity.DbSet<Citizen_TblZooVehicleDetail> Citizen_TblZooVehicleDetails { get; set; } // tbl_ZooVehicleDetails
        System.Data.Entity.DbSet<Citizen_ZooSeatInventoryOld> Citizen_ZooSeatInventoryOlds { get; set; } // ZooSeatInventory_OLD
        System.Data.Entity.DbSet<CompanyRagistration> CompanyRagistrations { get; set; } // CompanyRagistration
        System.Data.Entity.DbSet<GIS_TblMstFixedLandNocType> GIS_TblMstFixedLandNocTypes { get; set; } // tbl_mst_FixedLand_NOCTypes
        System.Data.Entity.DbSet<GIS_TblMstFixedPermissionPlant> GIS_TblMstFixedPermissionPlants { get; set; } // tbl_Mst_FixedPermission_Plant
        System.Data.Entity.DbSet<GIS_TblMstFixedPermissionPlantMapping> GIS_TblMstFixedPermissionPlantMappings { get; set; } // tbl_Mst_FixedPermission_PlantMapping
        System.Data.Entity.DbSet<GIS_TblMstFixedPermissionType> GIS_TblMstFixedPermissionTypes { get; set; } // tbl_mst_FixedPermissionTypes
        System.Data.Entity.DbSet<Master_TblMstAdminDivision> Master_TblMstAdminDivisions { get; set; } // tbl_mst_Admin_Division
        System.Data.Entity.DbSet<Master_TblMstDistrict> Master_TblMstDistricts { get; set; } // tbl_mst_Districts
        System.Data.Entity.DbSet<Master_TblMstEqptSanctuariesFee> Master_TblMstEqptSanctuariesFees { get; set; } // tbl_mst_Eqpt_SanctuariesFee
        System.Data.Entity.DbSet<Master_TblMstModeOfBooking> Master_TblMstModeOfBookings { get; set; } // tbl_mst_ModeOfBooking
        System.Data.Entity.DbSet<Master_TblMstPlace> Master_TblMstPlaces { get; set; } // tbl_mst_Places
        System.Data.Entity.DbSet<Master_TblMstPlaceBookingDuration> Master_TblMstPlaceBookingDurations { get; set; } // tbl_mst_PlaceBookingDuration
        System.Data.Entity.DbSet<Master_TblMstPlaceDisplay> Master_TblMstPlaceDisplays { get; set; } // tbl_Mst_PlaceDisplay
        System.Data.Entity.DbSet<Master_TblMstRecordStatu> Master_TblMstRecordStatus { get; set; } // tbl_Mst_RecordStatus
        System.Data.Entity.DbSet<Master_TblMstShiftType> Master_TblMstShiftTypes { get; set; } // tbl_Mst_ShiftType
        System.Data.Entity.DbSet<Master_TblMstTicketingFee> Master_TblMstTicketingFees { get; set; } // tbl_mst_TicketingFees
        System.Data.Entity.DbSet<Master_TblMstVehicleEquipment> Master_TblMstVehicleEquipments { get; set; } // tbl_mst_Vehicle_Equipment
        System.Data.Entity.DbSet<Master_TblMstVehicleEquipmentFee> Master_TblMstVehicleEquipmentFees { get; set; } // tbl_mst_Vehicle_EquipmentFee
        System.Data.Entity.DbSet<Master_TblMstWildLifeEqptFeeDetail> Master_TblMstWildLifeEqptFeeDetails { get; set; } // tbl_Mst_WildLifeEqptFeeDetails
        System.Data.Entity.DbSet<Master_TblMstWildLifeHeadDetail> Master_TblMstWildLifeHeadDetails { get; set; } // tbl_Mst_WildLifeHeadDetails
        System.Data.Entity.DbSet<Master_TblMstWildLifeHeadMaster> Master_TblMstWildLifeHeadMasters { get; set; } // tbl_Mst_WildLifeHeadMaster
        System.Data.Entity.DbSet<Master_TblMstWildLifeTicketFeeDetail> Master_TblMstWildLifeTicketFeeDetails { get; set; } // tbl_Mst_WildLifeTicketFeeDetails
        System.Data.Entity.DbSet<Master_TblMstZone> Master_TblMstZones { get; set; } // tbl_mst_Zone
        System.Data.Entity.DbSet<Master_TblZooHeadMaster> Master_TblZooHeadMasters { get; set; } // tbl_ZooHeadMaster
        System.Data.Entity.DbSet<Master_TblZooPlaceWiseHead> Master_TblZooPlaceWiseHeads { get; set; } // tbl_ZooPlaceWiseHead
        System.Data.Entity.DbSet<Master_TblZooSeatInventory> Master_TblZooSeatInventories { get; set; } // tbl_ZooSeatInventory
        System.Data.Entity.DbSet<Master_TblZooTicketHeaderFooter> Master_TblZooTicketHeaderFooters { get; set; } // tblZooTicketHeaderFooter
        System.Data.Entity.DbSet<Master_TblZooVehicleEquipment> Master_TblZooVehicleEquipments { get; set; } // tbl_Zoo_VehicleEquipment
        System.Data.Entity.DbSet<Master_TblZooVehicleFee> Master_TblZooVehicleFees { get; set; } // tbl_ZooVehicleFees
        System.Data.Entity.DbSet<Product> Products { get; set; } // Products
        System.Data.Entity.DbSet<TblMstDistrict> TblMstDistricts { get; set; } // tbl_mst_Districts
        System.Data.Entity.DbSet<TblMstPlace> TblMstPlaces { get; set; } // tbl_mst_Places
        System.Data.Entity.DbSet<TblUserProfile> TblUserProfiles { get; set; } // tbl_UserProfiles
        System.Data.Entity.DbSet<Token> Tokens { get; set; } // Tokens
        System.Data.Entity.DbSet<User> Users { get; set; } // User
        System.Data.Entity.DbSet<ZooSeatInventoryOld> ZooSeatInventoryOlds { get; set; } // ZooSeatInventory_OLD

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();

        // Stored Procedures
        System.Collections.Generic.List<AdminConfiguration_GetCompanyByUrlReturnModel> AdminConfiguration_GetCompanyByUrl(string url);
        System.Collections.Generic.List<AdminConfiguration_GetCompanyByUrlReturnModel> AdminConfiguration_GetCompanyByUrl(string url, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<AdminConfiguration_GetCompanyByUrlReturnModel>> AdminConfiguration_GetCompanyByUrlAsync(string url);

        System.Collections.Generic.List<Master_SpUpdateDistrictsReturnModel> Master_SpUpdateDistricts(string action, long? rowid, bool? status);
        System.Collections.Generic.List<Master_SpUpdateDistrictsReturnModel> Master_SpUpdateDistricts(string action, long? rowid, bool? status, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<Master_SpUpdateDistrictsReturnModel>> Master_SpUpdateDistrictsAsync(string action, long? rowid, bool? status);

    }

}
// </auto-generated>
