// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_ZooHeadMaster
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Master_TblZooHeadMaster
    {
        public int HeadId { get; set; } // HeadId (Primary key)
        public string HeadName { get; set; } // HeadName (length: 200)
        public bool IsActive { get; set; } // isActive
        public string CodeName { get; set; } // CodeName (length: 50)

        public Master_TblZooHeadMaster()
        {
            IsActive = true;
            CodeName = "";
        }
    }

}
// </auto-generated>
