// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_Mst_WildLifeHeadDetails
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Master_TblMstWildLifeHeadDetail
    {
        public int Rowid { get; set; } // ROWID (Primary key)
        public string HeadDetailName { get; set; } // HeadDetailName (length: 200)
        public int HeadId { get; set; } // HeadId
        public bool IsActive { get; set; } // isActive
        public string CodeName { get; set; } // CodeName (length: 50)
        public string Type { get; set; } // TYPE (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child Citizen_TblWildLifeSafariBookingDetails where [tbl_WildLifeSafariBookingDetails].[WildLifeHeadDetailID] point to this entity (0WildLifeHeadDetailsFK)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Citizen_TblWildLifeSafariBookingDetail> Citizen_TblWildLifeSafariBookingDetails { get; set; } // tbl_WildLifeSafariBookingDetails.0WildLifeHeadDetailsFK
        /// <summary>
        /// Child Citizen_TblWildLifeTicketBookingMemberDetails where [tbl_WildLifeTicketBookingMemberDetails].[WildLifeHeadDetailID] point to this entity (WildLifeHeadDetailsFK)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Citizen_TblWildLifeTicketBookingMemberDetail> Citizen_TblWildLifeTicketBookingMemberDetails { get; set; } // tbl_WildLifeTicketBookingMemberDetails.WildLifeHeadDetailsFK
        /// <summary>
        /// Child Master_TblMstWildLifeTicketFeeDetails where [tbl_Mst_WildLifeTicketFeeDetails].[WildLifeHeadDetailID] point to this entity (WildLifeHeadDetailsFK)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Master_TblMstWildLifeTicketFeeDetail> Master_TblMstWildLifeTicketFeeDetails { get; set; } // tbl_Mst_WildLifeTicketFeeDetails.WildLifeHeadDetailsFK

        // Foreign keys

        /// <summary>
        /// Parent Master_TblMstWildLifeHeadMaster pointed by [tbl_Mst_WildLifeHeadDetails].([HeadId]) (HeadIDFK)
        /// </summary>
        public virtual Master_TblMstWildLifeHeadMaster Master_TblMstWildLifeHeadMaster { get; set; } // HeadIDFK

        public Master_TblMstWildLifeHeadDetail()
        {
            HeadId = 0;
            IsActive = true;
            CodeName = "";
            Type = "";
            Master_TblMstWildLifeTicketFeeDetails = new System.Collections.Generic.List<Master_TblMstWildLifeTicketFeeDetail>();
            Citizen_TblWildLifeSafariBookingDetails = new System.Collections.Generic.List<Citizen_TblWildLifeSafariBookingDetail>();
            Citizen_TblWildLifeTicketBookingMemberDetails = new System.Collections.Generic.List<Citizen_TblWildLifeTicketBookingMemberDetail>();
        }
    }

}
// </auto-generated>
