// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_ZooVehicleFees
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Master_TblZooVehicleFeeConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Master_TblZooVehicleFee>
    {
        public Master_TblZooVehicleFeeConfiguration()
            : this("Master")
        {
        }

        public Master_TblZooVehicleFeeConfiguration(string schema)
        {
            ToTable("tbl_ZooVehicleFees", schema);
            HasKey(x => x.FeeId);

            Property(x => x.FeeId).HasColumnName(@"FeeId").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.PlaceId).HasColumnName(@"PlaceID").HasColumnType("bigint").IsRequired();
            Property(x => x.ZooVehicleId).HasColumnName(@"ZooVehicleID").HasColumnType("int").IsRequired();
            Property(x => x.FeePerVehicle).HasColumnName(@"FeePerVehicle").HasColumnType("decimal").IsRequired().HasPrecision(18,2);
            Property(x => x.NumberofVehicle).HasColumnName(@"NumberofVehicle").HasColumnType("int").IsRequired();
            Property(x => x.TotalFee).HasColumnName(@"TotalFee").HasColumnType("decimal").IsRequired().HasPrecision(18,2);
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();

            // Foreign keys
            HasRequired(a => a.Master_TblZooVehicleEquipment).WithMany(b => b.Master_TblZooVehicleFees).HasForeignKey(c => c.ZooVehicleId); // FK_tbl_ZooVehicleFees_tbl_Zoo_VehicleEquipment
        }
    }

}
// </auto-generated>
