// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // The table 'Tbl_Mst_PlaceWiseDivision' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // Tbl_Mst_PlaceWiseDivision
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Master_TblMstPlaceWiseDivision
    {
        public string HqCode { get; set; } // HQ_Code (length: 200)
        public string HqName { get; set; } // HQ_Name (length: 200)
        public string CircleCode { get; set; } // CIRCLE_CODE (length: 200)
        public string CircleName { get; set; } // CIRCLE_Name (length: 200)
        public string DivCode { get; set; } // DIV_CODE (length: 200)
        public string DivName { get; set; } // DIV_Name (length: 200)
        public int? DistrictCode { get; set; } // DISTRICT_CODE
        public string DistrictName { get; set; } // DISTRICT_Name (length: 200)
        public int? PlaceId { get; set; } // Place_ID
        public string PlaceName { get; set; } // Place_Name (length: 200)
    }

}
// </auto-generated>
