// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_Mst_WildLifeEqptFeeDetails
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Master_TblMstWildLifeEqptFeeDetail
    {
        public int Rowid { get; set; } // ROWID (Primary key)
        public long EqptId { get; set; } // EqptID
        public int WildLifeHeadDetailId { get; set; } // WildLifeHeadDetailID
        public double Price { get; set; } // Price
        public bool IsActive { get; set; } // isActive
    }

}
// </auto-generated>
