// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_mst_Admin_Division
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Master_TblMstAdminDivision
    {
        public int Id { get; set; } // ID
        public string DivisionCode { get; set; } // DIVISION_CODE (Primary key) (length: 10)
        public string DivisionName { get; set; } // DIVISION_NAME (length: 100)
        public string DivisionNameh { get; set; } // DIVISION_NAMEH (length: 100)

        // Reverse navigation

        /// <summary>
        /// Child Master_TblMstDistricts where [tbl_mst_Districts].[DIV_CODE] point to this entity (FK_tbl_mst_Districts_tbl_mst_Admin_Division)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Master_TblMstDistrict> Master_TblMstDistricts { get; set; } // tbl_mst_Districts.FK_tbl_mst_Districts_tbl_mst_Admin_Division

        public Master_TblMstAdminDivision()
        {
            Master_TblMstDistricts = new System.Collections.Generic.List<Master_TblMstDistrict>();
        }
    }

}
// </auto-generated>
