// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_ZooSeatInventory
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Master_TblZooSeatInventory
    {
        public int ZooSeatInventoryId { get; set; } // ZooSeatInventoryId (Primary key)
        public long PlaceId { get; set; } // PlaceId
        public int OnlineZooSeats { get; set; } // OnlineZooSeats
        public int OffLineZooSeats { get; set; } // OffLineZooSeats
        public bool IsActive { get; set; } // isActive
        public byte? ShiftType { get; set; } // ShiftType

        public Master_TblZooSeatInventory()
        {
            PlaceId = 0;
            OnlineZooSeats = 0;
            OffLineZooSeats = 0;
            IsActive = true;
            ShiftType = 0;
        }
    }

}
// </auto-generated>
