// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_mst_Vehicle_EquipmentFee
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Master_TblMstVehicleEquipmentFee
    {
        public long VehicleId { get; set; } // VehicleID (Primary key)
        public long? CategoryId { get; set; } // CategoryID
        public string Name { get; set; } // Name (length: 200)
        public decimal? Fees { get; set; } // Fees
        public int? Isactive { get; set; } // Isactive
        public System.DateTime? EnteredOn { get; set; } // EnteredOn
        public long? EnteredBy { get; set; } // EnteredBy
        public System.DateTime? UpdatedOn { get; set; } // UpdatedOn
        public long? UpdatedBy { get; set; } // UpdatedBy

        // Reverse navigation

        /// <summary>
        /// Parent (One-to-One) Master_TblMstVehicleEquipmentFee pointed by [tbl_mst_Eqpt_SanctuariesFee].[ID] (FK_VehicleCategoryNameID)
        /// </summary>
        public virtual Master_TblMstEqptSanctuariesFee Master_TblMstEqptSanctuariesFee { get; set; } // tbl_mst_Eqpt_SanctuariesFee.FK_VehicleCategoryNameID
        /// <summary>
        /// Child Citizen_TblSafariBookings where [tbl_SafariBooking].[VehicleID] point to this entity (FK_VehicleID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Citizen_TblSafariBooking> Citizen_TblSafariBookings { get; set; } // tbl_SafariBooking.FK_VehicleID

        // Foreign keys

        /// <summary>
        /// Parent Master_TblMstVehicleEquipment pointed by [tbl_mst_Vehicle_EquipmentFee].([CategoryId]) (FK_tbl_mst_Vehicle_EquipmentFee_tbl_mst_Vehicle_Equipment)
        /// </summary>
        public virtual Master_TblMstVehicleEquipment Master_TblMstVehicleEquipment { get; set; } // FK_tbl_mst_Vehicle_EquipmentFee_tbl_mst_Vehicle_Equipment

        public Master_TblMstVehicleEquipmentFee()
        {
            EnteredOn = System.DateTime.Now;
            Citizen_TblSafariBookings = new System.Collections.Generic.List<Citizen_TblSafariBooking>();
        }
    }

}
// </auto-generated>
