// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_ZooVehicleFees
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Master_TblZooVehicleFee
    {
        public long FeeId { get; set; } // FeeId (Primary key)
        public long PlaceId { get; set; } // PlaceID
        public int ZooVehicleId { get; set; } // ZooVehicleID
        public decimal FeePerVehicle { get; set; } // FeePerVehicle
        public int NumberofVehicle { get; set; } // NumberofVehicle
        public decimal TotalFee { get; set; } // TotalFee
        public bool IsActive { get; set; } // IsActive

        // Foreign keys

        /// <summary>
        /// Parent Master_TblZooVehicleEquipment pointed by [tbl_ZooVehicleFees].([ZooVehicleId]) (FK_tbl_ZooVehicleFees_tbl_Zoo_VehicleEquipment)
        /// </summary>
        public virtual Master_TblZooVehicleEquipment Master_TblZooVehicleEquipment { get; set; } // FK_tbl_ZooVehicleFees_tbl_Zoo_VehicleEquipment

        public Master_TblZooVehicleFee()
        {
            PlaceId = 0;
            ZooVehicleId = 0;
            FeePerVehicle = 0m;
            NumberofVehicle = 0;
            TotalFee = 0m;
            IsActive = true;
        }
    }

}
// </auto-generated>
