// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_mst_PlaceBookingDuration
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Master_TblMstPlaceBookingDuration
    {
        public int Id { get; set; } // ID (Primary key)
        public int PlaceId { get; set; } // PlaceID
        public int ZoneId { get; set; } // ZoneID
        public byte ModeOfBookingId { get; set; } // ModeOfBookingID
        public System.DateTime DurationFromDate { get; set; } // DurationFromDate
        public System.DateTime DurationToDate { get; set; } // DurationToDate
        public bool Isactive { get; set; } // Isactive

        // Foreign keys

        /// <summary>
        /// Parent Master_TblMstModeOfBooking pointed by [tbl_mst_PlaceBookingDuration].([ModeOfBookingId]) (MoodOfBooking)
        /// </summary>
        public virtual Master_TblMstModeOfBooking Master_TblMstModeOfBooking { get; set; } // MoodOfBooking
    }

}
// </auto-generated>
