// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tblZooTicketHeaderFooter
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Master_TblZooTicketHeaderFooterConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Master_TblZooTicketHeaderFooter>
    {
        public Master_TblZooTicketHeaderFooterConfiguration()
            : this("Master")
        {
        }

        public Master_TblZooTicketHeaderFooterConfiguration(string schema)
        {
            ToTable("tblZooTicketHeaderFooter", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.HeadeText).HasColumnName(@"HeadeText").HasColumnType("nvarchar").IsOptional().HasMaxLength(2000);
            Property(x => x.FooterText).HasColumnName(@"FooterText").HasColumnType("nvarchar").IsOptional().HasMaxLength(2000);
            Property(x => x.IsActive).HasColumnName(@"isActive").HasColumnType("bit").IsRequired();
            Property(x => x.PlaceId).HasColumnName(@"PlaceID").HasColumnType("bigint").IsRequired();
        }
    }

}
// </auto-generated>
