// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_mst_PlaceBookingDuration
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Master_TblMstPlaceBookingDurationConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Master_TblMstPlaceBookingDuration>
    {
        public Master_TblMstPlaceBookingDurationConfiguration()
            : this("Master")
        {
        }

        public Master_TblMstPlaceBookingDurationConfiguration(string schema)
        {
            ToTable("tbl_mst_PlaceBookingDuration", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.PlaceId).HasColumnName(@"PlaceID").HasColumnType("int").IsRequired();
            Property(x => x.ZoneId).HasColumnName(@"ZoneID").HasColumnType("int").IsRequired();
            Property(x => x.ModeOfBookingId).HasColumnName(@"ModeOfBookingID").HasColumnType("tinyint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.DurationFromDate).HasColumnName(@"DurationFromDate").HasColumnType("datetime").IsRequired();
            Property(x => x.DurationToDate).HasColumnName(@"DurationToDate").HasColumnType("datetime").IsRequired();
            Property(x => x.Isactive).HasColumnName(@"Isactive").HasColumnType("bit").IsRequired();

            // Foreign keys
            HasRequired(a => a.Master_TblMstModeOfBooking).WithMany(b => b.Master_TblMstPlaceBookingDurations).HasForeignKey(c => c.ModeOfBookingId).WillCascadeOnDelete(false); // MoodOfBooking
        }
    }

}
// </auto-generated>
