// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_mst_Vehicle_Equipment
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Master_TblMstVehicleEquipment
    {
        public long CategoryId { get; set; } // CategoryID (Primary key)
        public string CategoryName { get; set; } // CategoryName (length: 200)
        public bool? Isactive { get; set; } // Isactive
        public System.DateTime? EnteredOn { get; set; } // EnteredOn
        public long? EnteredBy { get; set; } // EnteredBy
        public System.DateTime? UpdatedOn { get; set; } // UpdatedOn
        public long? UpdatedBy { get; set; } // UpdatedBy

        // Reverse navigation

        /// <summary>
        /// Child Citizen_TblSafariBookings where [tbl_SafariBooking].[VehicleCatID] point to this entity (FK_VehicleCatID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Citizen_TblSafariBooking> Citizen_TblSafariBookings { get; set; } // tbl_SafariBooking.FK_VehicleCatID
        /// <summary>
        /// Child Master_TblMstEqptSanctuariesFees where [tbl_mst_Eqpt_SanctuariesFee].[VehicleCategoryID] point to this entity (FK_VehicleCategoryID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Master_TblMstEqptSanctuariesFee> Master_TblMstEqptSanctuariesFees { get; set; } // tbl_mst_Eqpt_SanctuariesFee.FK_VehicleCategoryID
        /// <summary>
        /// Child Master_TblMstVehicleEquipmentFees where [tbl_mst_Vehicle_EquipmentFee].[CategoryID] point to this entity (FK_tbl_mst_Vehicle_EquipmentFee_tbl_mst_Vehicle_Equipment)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Master_TblMstVehicleEquipmentFee> Master_TblMstVehicleEquipmentFees { get; set; } // tbl_mst_Vehicle_EquipmentFee.FK_tbl_mst_Vehicle_EquipmentFee_tbl_mst_Vehicle_Equipment

        public Master_TblMstVehicleEquipment()
        {
            UpdatedOn = System.DateTime.Now;
            Master_TblMstEqptSanctuariesFees = new System.Collections.Generic.List<Master_TblMstEqptSanctuariesFee>();
            Master_TblMstVehicleEquipmentFees = new System.Collections.Generic.List<Master_TblMstVehicleEquipmentFee>();
            Citizen_TblSafariBookings = new System.Collections.Generic.List<Citizen_TblSafariBooking>();
        }
    }

}
// </auto-generated>
