// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_Mst_WildLifeHeadMaster
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Master_TblMstWildLifeHeadMaster
    {
        public int HeadId { get; set; } // HeadId (Primary key)
        public string HeadName { get; set; } // HeadName (length: 200)
        public bool IsActive { get; set; } // isActive
        public string CodeName { get; set; } // CodeName (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child Master_TblMstWildLifeHeadDetails where [tbl_Mst_WildLifeHeadDetails].[HeadId] point to this entity (HeadIDFK)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Master_TblMstWildLifeHeadDetail> Master_TblMstWildLifeHeadDetails { get; set; } // tbl_Mst_WildLifeHeadDetails.HeadIDFK

        public Master_TblMstWildLifeHeadMaster()
        {
            IsActive = true;
            CodeName = "";
            Master_TblMstWildLifeHeadDetails = new System.Collections.Generic.List<Master_TblMstWildLifeHeadDetail>();
        }
    }

}
// </auto-generated>
