// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_Zoo_VehicleEquipment
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Master_TblZooVehicleEquipmentConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Master_TblZooVehicleEquipment>
    {
        public Master_TblZooVehicleEquipmentConfiguration()
            : this("Master")
        {
        }

        public Master_TblZooVehicleEquipmentConfiguration(string schema)
        {
            ToTable("tbl_Zoo_VehicleEquipment", schema);
            HasKey(x => x.ZooVehicleId);

            Property(x => x.ZooVehicleId).HasColumnName(@"ZooVehicleID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.CategoryId).HasColumnName(@"CategoryID").HasColumnType("bigint").IsRequired();
            Property(x => x.VehicleName).HasColumnName(@"VehicleName").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(200);
            Property(x => x.Isactive).HasColumnName(@"Isactive").HasColumnType("bit").IsRequired();
        }
    }

}
// </auto-generated>
