// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_ZooSeatInventory
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Master_TblZooSeatInventoryConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Master_TblZooSeatInventory>
    {
        public Master_TblZooSeatInventoryConfiguration()
            : this("Master")
        {
        }

        public Master_TblZooSeatInventoryConfiguration(string schema)
        {
            ToTable("tbl_ZooSeatInventory", schema);
            HasKey(x => x.ZooSeatInventoryId);

            Property(x => x.ZooSeatInventoryId).HasColumnName(@"ZooSeatInventoryId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.PlaceId).HasColumnName(@"PlaceId").HasColumnType("bigint").IsRequired();
            Property(x => x.OnlineZooSeats).HasColumnName(@"OnlineZooSeats").HasColumnType("int").IsRequired();
            Property(x => x.OffLineZooSeats).HasColumnName(@"OffLineZooSeats").HasColumnType("int").IsRequired();
            Property(x => x.IsActive).HasColumnName(@"isActive").HasColumnType("bit").IsRequired();
            Property(x => x.ShiftType).HasColumnName(@"ShiftType").HasColumnType("tinyint").IsOptional();
        }
    }

}
// </auto-generated>
