// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_Mst_WildLifeHeadMaster
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Master_TblMstWildLifeHeadMasterConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Master_TblMstWildLifeHeadMaster>
    {
        public Master_TblMstWildLifeHeadMasterConfiguration()
            : this("Master")
        {
        }

        public Master_TblMstWildLifeHeadMasterConfiguration(string schema)
        {
            ToTable("tbl_Mst_WildLifeHeadMaster", schema);
            HasKey(x => x.HeadId);

            Property(x => x.HeadId).HasColumnName(@"HeadId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.HeadName).HasColumnName(@"HeadName").HasColumnType("nvarchar").IsOptional().HasMaxLength(200);
            Property(x => x.IsActive).HasColumnName(@"isActive").HasColumnType("bit").IsRequired();
            Property(x => x.CodeName).HasColumnName(@"CodeName").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
        }
    }

}
// </auto-generated>
