// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Master_SpUpdateDistrictsReturnModel
    {
        public System.Int32 ROWID { get; set; }
        public System.String STATE_CODE { get; set; }
        public System.String DIST_CODE { get; set; }
        public System.String DIST_NAME { get; set; }
        public System.Boolean ISOrganisingCamp { get; set; }
        public System.Boolean? IsActive { get; set; }
    }

}
// </auto-generated>
