// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_mst_Zone
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Master_TblMstZone
    {
        public long ZoneId { get; set; } // ZoneID (Primary key)
        public long PlaceId { get; set; } // PlaceID (Primary key)
        public string ZoneName { get; set; } // ZoneName (Primary key) (length: 100)
        public int TicketAllocatedPerShift { get; set; } // TicketAllocatedPerShift (Primary key)
        public int SeatsForCitizen { get; set; } // SeatsForCitizen (Primary key)
        public string ShiftTypeId { get; set; } // ShiftTypeID (Primary key) (length: 50)
        public bool Isactive { get; set; } // Isactive (Primary key)
        public System.DateTime EnteredOn { get; set; } // EnteredOn (Primary key)
        public long EnteredBy { get; set; } // EnteredBy (Primary key)
        public System.DateTime UpdatedOn { get; set; } // UpdatedOn (Primary key)
        public long UpdatedBy { get; set; } // UpdatedBy (Primary key)

        public Master_TblMstZone()
        {
            PlaceId = 0;
            ZoneName = "";
            TicketAllocatedPerShift = 0;
            SeatsForCitizen = 0;
            ShiftTypeId = "";
            Isactive = true;
            EnteredOn = System.DateTime.Now;
            EnteredBy = 0;
            UpdatedOn = System.DateTime.Now;
            UpdatedBy = 0;
        }
    }

}
// </auto-generated>
