// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_Mst_RecordStatus
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Master_TblMstRecordStatuConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Master_TblMstRecordStatu>
    {
        public Master_TblMstRecordStatuConfiguration()
            : this("Master")
        {
        }

        public Master_TblMstRecordStatuConfiguration(string schema)
        {
            ToTable("tbl_Mst_RecordStatus", schema);
            HasKey(x => x.Isactive);

            Property(x => x.Rowid).HasColumnName(@"ROWID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Isactive).HasColumnName(@"Isactive").HasColumnType("bit").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
        }
    }

}
// </auto-generated>
