// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_Mst_WildLifeTicketFeeDetails
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Master_TblMstWildLifeTicketFeeDetail
    {
        public int Rowid { get; set; } // ROWID (Primary key)
        public long FeesId { get; set; } // FeesID
        public int WildLifeHeadDetailId { get; set; } // WildLifeHeadDetailID
        public double Price { get; set; } // Price
        public bool IsActive { get; set; } // isActive

        // Foreign keys

        /// <summary>
        /// Parent Master_TblMstTicketingFee pointed by [tbl_Mst_WildLifeTicketFeeDetails].([FeesId]) (FEESIDPK)
        /// </summary>
        public virtual Master_TblMstTicketingFee Master_TblMstTicketingFee { get; set; } // FEESIDPK
        /// <summary>
        /// Parent Master_TblMstWildLifeHeadDetail pointed by [tbl_Mst_WildLifeTicketFeeDetails].([WildLifeHeadDetailId]) (WildLifeHeadDetailsFK)
        /// </summary>
        public virtual Master_TblMstWildLifeHeadDetail Master_TblMstWildLifeHeadDetail { get; set; } // WildLifeHeadDetailsFK

        public Master_TblMstWildLifeTicketFeeDetail()
        {
            FeesId = 0;
            WildLifeHeadDetailId = 0;
            Price = 0;
            IsActive = true;
        }
    }

}
// </auto-generated>
