// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_mst_Districts
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Master_TblMstDistrict
    {
        public int Rowid { get; set; } // ROWID
        public string StateCode { get; set; } // STATE_CODE (length: 2)
        public string DivCode { get; set; } // DIV_CODE (length: 10)
        public string DistCode { get; set; } // DIST_CODE (Primary key) (length: 10)
        public string DistName { get; set; } // DIST_NAME (length: 50)
        public string DistHname { get; set; } // DIST_HNAME
        public double? AreaSqkm { get; set; } // AREA_SQKM
        public bool? IsActive { get; set; } // IsActive
        public bool IsOrganisingCamp { get; set; } // ISOrganisingCamp

        // Reverse navigation

        /// <summary>
        /// Child Master_TblMstPlaces where [tbl_mst_Places].[DIST_CODE] point to this entity (FK_DIST_CODE)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Master_TblMstPlace> Master_TblMstPlaces { get; set; } // tbl_mst_Places.FK_DIST_CODE
        /// <summary>
        /// Child Master_TblMstTicketingFees where [tbl_mst_TicketingFees].[DIST_CODE] point to this entity (FK_tbl_mst_TicketingFees_tbl_mst_Districts)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Master_TblMstTicketingFee> Master_TblMstTicketingFees { get; set; } // tbl_mst_TicketingFees.FK_tbl_mst_TicketingFees_tbl_mst_Districts

        // Foreign keys

        /// <summary>
        /// Parent Master_TblMstAdminDivision pointed by [tbl_mst_Districts].([DivCode]) (FK_tbl_mst_Districts_tbl_mst_Admin_Division)
        /// </summary>
        public virtual Master_TblMstAdminDivision Master_TblMstAdminDivision { get; set; } // FK_tbl_mst_Districts_tbl_mst_Admin_Division

        public Master_TblMstDistrict()
        {
            IsActive = true;
            IsOrganisingCamp = false;
            Master_TblMstPlaces = new System.Collections.Generic.List<Master_TblMstPlace>();
            Master_TblMstTicketingFees = new System.Collections.Generic.List<Master_TblMstTicketingFee>();
        }
    }

}
// </auto-generated>
