// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_mst_Places
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Master_TblMstPlaceConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Master_TblMstPlace>
    {
        public Master_TblMstPlaceConfiguration()
            : this("Master")
        {
        }

        public Master_TblMstPlaceConfiguration(string schema)
        {
            ToTable("tbl_mst_Places", schema);
            HasKey(x => x.PlaceId);

            Property(x => x.PlaceId).HasColumnName(@"PlaceID").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.DistCode).HasColumnName(@"DIST_CODE").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(10);
            Property(x => x.PlaceName).HasColumnName(@"PlaceName").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(200);
            Property(x => x.Category).HasColumnName(@"Category").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Code).HasColumnName(@"Code").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(10);
            Property(x => x.ShiftTypeId).HasColumnName(@"ShiftTypeID").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.PlaceDisplayIDs).HasColumnName(@"PlaceDisplayIDs").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.IsAccommodation).HasColumnName(@"IsAccommodation").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.IsSafari).HasColumnName(@"IsSafari").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.IsZone).HasColumnName(@"IsZone").HasColumnType("bit").IsRequired();
            Property(x => x.TicketAllocatedPerShift).HasColumnName(@"TicketAllocatedPerShift").HasColumnType("int").IsRequired();
            Property(x => x.MaxBookingDuration).HasColumnName(@"MaxBookingDuration").HasColumnType("int").IsRequired();
            Property(x => x.Tax).HasColumnName(@"Tax").HasColumnType("decimal").IsRequired().HasPrecision(18,2);
            Property(x => x.EmitraCharges).HasColumnName(@"EmitraCharges").HasColumnType("decimal").IsRequired().HasPrecision(18,2);
            Property(x => x.ContactPerson).HasColumnName(@"ContactPerson").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.Address).HasColumnName(@"Address").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(500);
            Property(x => x.PhoneNo).HasColumnName(@"PhoneNo").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(30);
            Property(x => x.BoardingPoint).HasColumnName(@"Boarding_Point").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(500);
            Property(x => x.Isactive).HasColumnName(@"Isactive").HasColumnType("bit").IsRequired();
            Property(x => x.EnteredOn).HasColumnName(@"EnteredOn").HasColumnType("datetime").IsRequired();
            Property(x => x.EnteredBy).HasColumnName(@"EnteredBy").HasColumnType("bigint").IsRequired();
            Property(x => x.UpdatedOn).HasColumnName(@"UpdatedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.UpdatedBy).HasColumnName(@"UpdatedBy").HasColumnType("bigint").IsRequired();

            // Foreign keys
            HasRequired(a => a.Master_TblMstDistrict).WithMany(b => b.Master_TblMstPlaces).HasForeignKey(c => c.DistCode).WillCascadeOnDelete(false); // FK_DIST_CODE
        }
    }

}
// </auto-generated>
