// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_mst_ModeOfBooking
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Master_TblMstModeOfBooking
    {
        public byte Id { get; set; } // ID (Primary key)
        public string Name { get; set; } // NAME (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child Master_TblMstPlaceBookingDurations where [tbl_mst_PlaceBookingDuration].[ModeOfBookingID] point to this entity (MoodOfBooking)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Master_TblMstPlaceBookingDuration> Master_TblMstPlaceBookingDurations { get; set; } // tbl_mst_PlaceBookingDuration.MoodOfBooking

        public Master_TblMstModeOfBooking()
        {
            Name = "";
            Master_TblMstPlaceBookingDurations = new System.Collections.Generic.List<Master_TblMstPlaceBookingDuration>();
        }
    }

}
// </auto-generated>
