// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_mst_Districts
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class TblMstDistrict
    {
        public int Rowid { get; set; } // ROWID
        public string DistCode { get; set; } // DIST_CODE (Primary key) (length: 10)
        public string StateCode { get; set; } // STATE_CODE (length: 2)
        public string DivCode { get; set; } // DIV_CODE (length: 10)
        public string DistName { get; set; } // DIST_NAME (length: 50)
        public string DistHname { get; set; } // DIST_HNAME
        public double? AreaSqkm { get; set; } // AREA_SQKM
        public bool? IsActive { get; set; } // IsActive
        public bool IsOrganisingCamp { get; set; } // ISOrganisingCamp

        // Reverse navigation

        /// <summary>
        /// Child TblMstPlaces where [tbl_mst_Places].[DIST_CODE] point to this entity (FK_tbl_mst_Places_tbl_mst_Districts)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TblMstPlace> TblMstPlaces { get; set; } // tbl_mst_Places.FK_tbl_mst_Places_tbl_mst_Districts

        public TblMstDistrict()
        {
            IsActive = true;
            IsOrganisingCamp = false;
            TblMstPlaces = new System.Collections.Generic.List<TblMstPlace>();
        }
    }

}
// </auto-generated>
