// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_mst_Places
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class TblMstPlaceConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<TblMstPlace>
    {
        public TblMstPlaceConfiguration()
            : this("dbo")
        {
        }

        public TblMstPlaceConfiguration(string schema)
        {
            ToTable("tbl_mst_Places", schema);
            HasKey(x => x.PlaceId);

            Property(x => x.PlaceId).HasColumnName(@"PlaceID").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.DistCode).HasColumnName(@"DIST_CODE").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(10);
            Property(x => x.PlaceName).HasColumnName(@"PlaceName").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(200);
            Property(x => x.Category).HasColumnName(@"Category").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.MorningShiftFrom).HasColumnName(@"MorningShiftFrom").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.MorningShiftTo).HasColumnName(@"MorningShiftTo").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.EveningShiftFrom).HasColumnName(@"EveningShiftFrom").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.EveningShiftTo).HasColumnName(@"EveningShiftTo").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.FullDayShift).HasColumnName(@"FullDayShift").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(10);
            Property(x => x.TicketAllocatedPerShift).HasColumnName(@"TicketAllocatedPerShift").HasColumnType("int").IsOptional();
            Property(x => x.IsAccommodation).HasColumnName(@"IsAccommodation").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.IsSafari).HasColumnName(@"IsSafari").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Isactive).HasColumnName(@"Isactive").HasColumnType("int").IsOptional();
            Property(x => x.EnteredOn).HasColumnName(@"EnteredOn").HasColumnType("datetime").IsOptional();
            Property(x => x.EnteredBy).HasColumnName(@"EnteredBy").HasColumnType("bigint").IsOptional();
            Property(x => x.UpdatedOn).HasColumnName(@"UpdatedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.UpdatedBy).HasColumnName(@"UpdatedBy").HasColumnType("bigint").IsOptional();
            Property(x => x.IsZone).HasColumnName(@"IsZone").HasColumnType("bit").IsOptional();
            Property(x => x.ContactPerson).HasColumnName(@"ContactPerson").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.Address).HasColumnName(@"Address").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(500);
            Property(x => x.PhoneNo).HasColumnName(@"PhoneNo").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(30);
            Property(x => x.BoardingPoint).HasColumnName(@"Boarding_Point").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(500);
            Property(x => x.IsOnlineBooking).HasColumnName(@"IsOnlineBooking").HasColumnType("bit").IsRequired();
            Property(x => x.IsCamping).HasColumnName(@"IsCamping").HasColumnType("bit").IsRequired();
            Property(x => x.IsResearch).HasColumnName(@"IsResearch").HasColumnType("bit").IsRequired();
            Property(x => x.MaxBookingDuration).HasColumnName(@"MaxBookingDuration").HasColumnType("int").IsRequired();
            Property(x => x.IsMorning).HasColumnName(@"isMorning").HasColumnType("bit").IsOptional();
            Property(x => x.IsEvening).HasColumnName(@"isEvening").HasColumnType("bit").IsOptional();
            Property(x => x.IsFullDay).HasColumnName(@"isFullDay").HasColumnType("bit").IsOptional();
            Property(x => x.IsDptKiosk).HasColumnName(@"isDptKiosk").HasColumnType("bit").IsOptional();
            Property(x => x.IsCitizen).HasColumnName(@"isCitizen").HasColumnType("bit").IsOptional();
            Property(x => x.Tax).HasColumnName(@"Tax").HasColumnType("decimal").IsRequired().HasPrecision(18,2);
            Property(x => x.EmitraCharges).HasColumnName(@"EmitraCharges").HasColumnType("decimal").IsRequired().HasPrecision(18,2);
            Property(x => x.Code).HasColumnName(@"Code").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(10);
            Property(x => x.IsZooAvailable).HasColumnName(@"isZooAvailable").HasColumnType("bit").IsRequired();
            Property(x => x.IsFilmShootong).HasColumnName(@"isFilmShootong").HasColumnType("bit").IsRequired();

            // Foreign keys
            HasRequired(a => a.TblMstDistrict).WithMany(b => b.TblMstPlaces).HasForeignKey(c => c.DistCode); // FK_tbl_mst_Places_tbl_mst_Districts
        }
    }

}
// </auto-generated>
