// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_mst_Districts
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class TblMstDistrictConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<TblMstDistrict>
    {
        public TblMstDistrictConfiguration()
            : this("dbo")
        {
        }

        public TblMstDistrictConfiguration(string schema)
        {
            ToTable("tbl_mst_Districts", schema);
            HasKey(x => x.DistCode);

            Property(x => x.Rowid).HasColumnName(@"ROWID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.DistCode).HasColumnName(@"DIST_CODE").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(10).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.StateCode).HasColumnName(@"STATE_CODE").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(2);
            Property(x => x.DivCode).HasColumnName(@"DIV_CODE").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(10);
            Property(x => x.DistName).HasColumnName(@"DIST_NAME").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.DistHname).HasColumnName(@"DIST_HNAME").HasColumnType("nvarchar(max)").IsRequired();
            Property(x => x.AreaSqkm).HasColumnName(@"AREA_SQKM").HasColumnType("float").IsOptional();
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsOptional();
            Property(x => x.IsOrganisingCamp).HasColumnName(@"ISOrganisingCamp").HasColumnType("bit").IsRequired();
        }
    }

}
// </auto-generated>
