// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_UserProfiles
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class TblUserProfileConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<TblUserProfile>
    {
        public TblUserProfileConfiguration()
            : this("dbo")
        {
        }

        public TblUserProfileConfiguration(string schema)
        {
            ToTable("tbl_UserProfiles", schema);
            HasKey(x => x.UserId);

            Property(x => x.UserId).HasColumnName(@"UserID").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.MemberId).HasColumnName(@"MemberID").HasColumnType("nvarchar").IsRequired().HasMaxLength(128);
            Property(x => x.Ssoid).HasColumnName(@"Ssoid").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.EmailId).HasColumnName(@"EmailId").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.Mobile).HasColumnName(@"Mobile").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(15);
            Property(x => x.Designation).HasColumnName(@"Designation").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(10);
            Property(x => x.Dob).HasColumnName(@"DOB").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.Gender).HasColumnName(@"Gender").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(10);
            Property(x => x.PostalAddress1).HasColumnName(@"Postal_Address1").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.PostalCode1).HasColumnName(@"Postal_Code1").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(10);
            Property(x => x.District1).HasColumnName(@"District1").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.PostalAddress2).HasColumnName(@"Postal_Address2").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.PostalCode2).HasColumnName(@"Postal_Code2").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.District2).HasColumnName(@"District2").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.City2).HasColumnName(@"City2").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.BhamashahId).HasColumnName(@"Bhamashah_Id").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.AadharId).HasColumnName(@"Aadhar_ID").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(12);
            Property(x => x.IsKioskUser).HasColumnName(@"IsKioskUser").HasColumnType("bit").IsRequired();
            Property(x => x.IsAgency).HasColumnName(@"IsAgency").HasColumnType("bit").IsRequired();
            Property(x => x.AgencyName).HasColumnName(@"AgencyName").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.AgencyDistrict).HasColumnName(@"AgencyDistrict").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.AgencyCity).HasColumnName(@"AgencyCity").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.AgencyAddress).HasColumnName(@"AgencyAddress").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.AgencySpoc).HasColumnName(@"AgencySPOC").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.AgencyContact).HasColumnName(@"AgencyContact").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.IsActive).HasColumnName(@"ISActive").HasColumnType("int").IsRequired();
            Property(x => x.EnteredOn).HasColumnName(@"EnteredOn").HasColumnType("datetime").IsRequired();
            Property(x => x.UpdatedOn).HasColumnName(@"UpdatedOn").HasColumnType("datetime").IsRequired();
            Property(x => x.UpdatedBy).HasColumnName(@"UpdatedBy").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.IsSso).HasColumnName(@"IsSSO").HasColumnType("bit").IsRequired();
            Property(x => x.IsBhamashah).HasColumnName(@"IsBhamashah").HasColumnType("bit").IsRequired();
        }
    }

}
// </auto-generated>
