// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // tbl_UserProfiles
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class TblUserProfile
    {
        public long UserId { get; set; } // UserID (Primary key)
        public string MemberId { get; set; } // MemberID (length: 128)
        public string Ssoid { get; set; } // Ssoid (length: 50)
        public string Name { get; set; } // Name (length: 100)
        public string EmailId { get; set; } // EmailId (length: 100)
        public string Mobile { get; set; } // Mobile (length: 15)
        public string Designation { get; set; } // Designation (length: 10)
        public string Dob { get; set; } // DOB (length: 100)
        public string Gender { get; set; } // Gender (length: 10)
        public string PostalAddress1 { get; set; } // Postal_Address1
        public string PostalCode1 { get; set; } // Postal_Code1 (length: 10)
        public string District1 { get; set; } // District1 (length: 20)
        public string PostalAddress2 { get; set; } // Postal_Address2
        public string PostalCode2 { get; set; } // Postal_Code2 (length: 50)
        public string District2 { get; set; } // District2 (length: 20)
        public string City2 { get; set; } // City2 (length: 50)
        public string BhamashahId { get; set; } // Bhamashah_Id (length: 20)
        public string AadharId { get; set; } // Aadhar_ID (length: 12)
        public bool IsKioskUser { get; set; } // IsKioskUser
        public bool IsAgency { get; set; } // IsAgency
        public string AgencyName { get; set; } // AgencyName (length: 50)
        public string AgencyDistrict { get; set; } // AgencyDistrict (length: 50)
        public string AgencyCity { get; set; } // AgencyCity (length: 50)
        public string AgencyAddress { get; set; } // AgencyAddress
        public string AgencySpoc { get; set; } // AgencySPOC (length: 50)
        public string AgencyContact { get; set; } // AgencyContact (length: 20)
        public int IsActive { get; set; } // ISActive
        public System.DateTime EnteredOn { get; set; } // EnteredOn
        public System.DateTime UpdatedOn { get; set; } // UpdatedOn
        public string UpdatedBy { get; set; } // UpdatedBy (length: 50)
        public bool IsSso { get; set; } // IsSSO
        public bool IsBhamashah { get; set; } // IsBhamashah

        public TblUserProfile()
        {
            IsKioskUser = false;
            IsAgency = false;
            IsActive = 1;
            EnteredOn = System.DateTime.Now;
            UpdatedOn = System.DateTime.Now;
            IsSso = true;
            IsBhamashah = false;
        }
    }

}
// </auto-generated>
