// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace FMDSS.Models
{

    // Tokens
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class Token
    {
        public int TokenId { get; set; } // TokenId (Primary key)
        public int UserId { get; set; } // UserId
        public string AuthToken { get; set; } // AuthToken (length: 250)
        public System.DateTime IssuedOn { get; set; } // IssuedOn
        public System.DateTime ExpiresOn { get; set; } // ExpiresOn

        // Foreign keys

        /// <summary>
        /// Parent User pointed by [Tokens].([UserId]) (FK_Tokens_User)
        /// </summary>
        public virtual User User { get; set; } // FK_Tokens_User
    }

}
// </auto-generated>
